#!/bin/bash

# =============================================
# This script copy the data generated by Run.sh
#
# Shule Yu
# Oct 18 2015
# =============================================

mkdir -p ${WORKDIR}/${EQ}
trap "rm -rf ${WORKDIR}/${EQ} ${WORKDIR}/*_${RunNumber}*; exit 1" SIGINT

# ==================================================
#              ! Work Begin !
# ==================================================

${BASHCODEDIR}/select_sac_data.sh ${DATADIR}/${EQ} RTZ > tmpfile_filelist_${RunNumber}

if ! [ -e tmpfile_filelist_${RunNumber} ]
then
	exit 1
else
	rsync -a --delete `cat tmpfile_filelist_${RunNumber}` ${WORKDIR}/${EQ}
fi

cd ${CODEDIR}

exit 0
